CREATE TABLE IF NOT EXISTS tasks(id INTEGER PRIMARY KEY, title TEXT, agent TEXT, prompt TEXT, status TEXT DEFAULT 'inbox');
CREATE TABLE IF NOT EXISTS runs(id INTEGER PRIMARY KEY, task_id INTEGER, agent TEXT, status TEXT);
CREATE TABLE IF NOT EXISTS logs(id INTEGER PRIMARY KEY, run_id INTEGER, line TEXT);
